### ISSUE TITLE
Add linter to enforce code style

### ISSUE THREAD

**Issue by nathfreder** [Passok11/todo-list-node-cli#11]
I would like to add a linter to enforce your code style. I think this will be helpful since you are asking for newcomers to contribute. Would this be worth the effort? 🥇 

![giphy](https://media.giphy.com/media/3o85xvK5MeEpMN9PWw/giphy.gif)

**Comment by nathfreder** [comment]
This would also come with [`prettier`](https://prettier.io/).

**Comment by nathfreder** [comment]
Great, I take it that this has been approved. @Passok11

**Comment by Passok11** [comment]
This will be very helpful.

Good luck in the task!

**Comment by gattigaga** [comment]
@Passok11  I was add it with Standard linting and Prettier in new PR.

**Comment by lopno** [comment]
Created a PR for the formatting with prettier https://github.com/Passok11/todo-list-node-cli/pull/16

**Comment by nathfreder** [comment]
Kind of disappointed that others took it before me, but that is okay. All the current pull requests do not work very well with the current codebase.
