### ISSUE TITLE
Help menu title is not showing properly on my machine

### ISSUE THREAD

**Issue by ywpark1** [Passok11/todo-list-node-cli#30]
I am running this on zsh with "agnoster" theme.

When I open the help menu, the title is hidden by the background color :

![file1](https://user-images.githubusercontent.com/20958399/46447901-64f7b080-c752-11e8-9d50-94163a6bf307.png)

If you do not mind, can I change the help menu title text color to white? It is really simple.

**Comment by Passok11** [comment]
Thanks for the pull request!
